### ISSUE TITLE
TypeError: Cannot read property 'rules' of undefined

### ISSUE THREAD

**Issue by oparisy** [harc/ohm#238]
I get this error while reading the value of the `message` property of a `MatchFailure`.

Using a debugger, my understanding is that this is caused by `pexprs.Apply.prototype.toFailure` being called without a `grammar` argument.

Indeed in my case `toFailure` seems called without `grammar` being passed to it:
```javascript
pexprs.Alt.prototype.toFailure = function(grammar) {
  var fs = this.terms.map(function(t) { return t.toFailure(); });
```

If I do not try to read the `message` property, I get no crash... but no help in fixing my grammar either.

I am willing to provide my grammar and test case, should that be of any help.

Regards,
Olivier.

**Comment by melloc** [comment]
I'm seeing the same issue:

```
% node crash.js

TypeError: Cannot read property 'rules' of undefined
    at Apply.pexprs.Apply.toFailure (/home/cody/src/node-jiramark/node_modules/ohm-js/src/pexprs-toFailure.js:46:28)
    at /home/cody/src/node-jiramark/node_modules/ohm-js/src/pexprs-toFailure.js:59:50
    at Array.map (native)
    at Alt.pexprs.Alt.toFailure (/home/cody/src/node-jiramark/node_modules/ohm-js/src/pexprs-toFailure.js:59:23)
    at Not.pexprs.Not.toFailure (/home/cody/src/node-jiramark/node_modules/ohm-js/src/pexprs-toFailure.js:37:26)
    at Object.MatchState.processFailure (/home/cody/src/node-jiramark/node_modules/ohm-js/src/MatchState.js:176:31)
    at Not.pexprs.Not.eval (/home/cody/src/node-jiramark/node_modules/ohm-js/src/pexprs-eval.js:181:11)
    at Object.MatchState.eval (/home/cody/src/node-jiramark/node_modules/ohm-js/src/MatchState.js:310:20)
    at Seq.pexprs.Seq.eval (/home/cody/src/node-jiramark/node_modules/ohm-js/src/pexprs-eval.js:111:16)
    at Object.MatchState.eval (/home/cody/src/node-jiramark/node_modules/ohm-js/src/MatchState.js:310:20)
```

I managed to get my program down to this example:

```
var ohm = require('ohm-js');

var source = [
    'Crash {',
    '  Words = Word+',
    '',
    '  Word',
    '   = "[" ident+ "|" uri "]" -- link1',
    '   | ident',
    '',
    '  reserved = "{" | "}"',
    '',
    '  ident = regchar+',
    '',
    '  regchar = ~(space | reserved) any',
    '',
    '  uri = (alnum | "\u0023".."\u002F" | ":" | "_")+',
    '}'
].join('\n');

var grammar = ohm.grammar(source);

var contents = '[example|https://example.com]{'
var m = grammar.match(contents);
if (m.failed()) {
    console.log(m.shortMessage);
} else {
    console.log('Input matched grammar');
}
```

**Comment by melloc** [comment]
I can confirm that passing `grammar` in `pexprs.Alt.prototype.toFailure` fixes the issue. It looks like it should also be passed in `pexprs.Seq.prototype.toFailure` and `pexprs.Iter.prototype.toFailure`.

**Comment by pdubroy** [comment]
@oparisy: A PR would be most welcome! And yes, a small unit test would be nice. No need to wait on the TypeScript rewrite — a bug like this is always worth fixing. Worst case, I will have a merge conflict :-)

**Comment by oparisy** [comment]
@pdubroy pleased to read it! @melloc, would you be OK with me using your example as the basis of a unit test?

**Comment by melloc** [comment]
@oparisy That's fine by me! Thanks for putting together a PR.

**Comment by pranaygp** [comment]
Running into the same issue more than a year later, and it seems versions `0.15.0` and `0.15.1` were pushed to github, but not npm

cc @pdubroy
