### ISSUE TITLE
Obscure runtime error: TypeError: cannot apply Semantics to [match failed at position 0] 

### ISSUE THREAD

**Issue by pmkary** [harc/ohm#240]
I get this obscure error within my runtime. The code is TypeScript so it probably should not have type error on my side:

```
<source-code-dir>/node_modules/ohm-js/src/Semantics.js:520
      throw new TypeError('cannot apply Semantics to ' + matchResult.toString());
      ^

TypeError: cannot apply Semantics to [match failed at position 0]
    at ASemantics (/Users/pmk/Codes/SugarPine/node_modules/ohm-js/src/Semantics.js:520:13)
    at Object.parse (/Users/pmk/Codes/SugarPine/bin/sugarpine.js:596:25)
    at Object.<anonymous> (/Users/pmk/Codes/SugarPine/debug/main.js:17:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
```

Since I could not understand the error, and it's code that is broken on your side I did not know what information to provide here actually. I can provide more information, just tell me on what.

**Comment by yoshikiohshima** [comment]
It looks like the parsing failed but you are applying the semantic action without checking.

```
let match = g.match(string, rule);
if (!match.succeeded()) {
    let errorObj = ...;
   throw errorObj;
}

let result = semantics(match);
```

**Comment by pmkary** [comment]
@yoshikiohshima thanks a lot, it solved the problem 👍
